# Generated by Django 3.0.4 on 2020-03-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='media/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('p_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50, null=True)),
                ('p_surname', models.CharField(max_length=50, null=True)),
                ('p_tel', models.CharField(max_length=10, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'DJANGO_TEST',
            },
        ),
    ]
